"""initial schema

Revision ID: 08f7039bd707
Revises: 
Create Date: 2026-09-27 19:05:31.090638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.types


# revision identifiers, used by Alembic.
revision: str = '08f7039bd707'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('minor_units', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    sqlite_strict=True
    )
    op.create_table('import_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('match', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_strict=True
    )
    op.create_table('setting',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key'),
    sqlite_strict=True
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('totp_secret', sa.Text(), nullable=True),
    sa.Column('locale', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.CheckConstraint("locale IN ('en','ru')", name='ck_user_locale'),
    sa.CheckConstraint("role IN ('admin','member')", name='ck_user_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sqlite_strict=True
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('institution', sa.Text(), nullable=True),
    sa.Column('opening_date', app.db.types.ISODate(), nullable=False),
    sa.Column('opening_balance', sa.Integer(), nullable=False),
    sa.Column('include_in_net_worth', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('archived_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.CheckConstraint("type IN ('current','savings','cash','credit_card','investment')", name='ck_account_type'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['currency'], ['currency.code'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sqlite_strict=True
    )
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('acquired_date', app.db.types.ISODate(), nullable=True),
    sa.Column('acquired_value', sa.Integer(), nullable=True),
    sa.Column('disposed_date', app.db.types.ISODate(), nullable=True),
    sa.Column('disposed_value', sa.Integer(), nullable=True),
    sa.Column('include_in_net_worth', sa.Integer(), nullable=False),
    sa.Column('archived_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.CheckConstraint("type IN ('real_estate','vehicle','other')", name='ck_asset_type'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['currency'], ['currency.code'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sqlite_strict=True
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('entity', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('diff', sa.Text(), nullable=True),
    sa.CheckConstraint("action IN ('create','update','delete')", name='ck_audit_log_action'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_strict=True
    )
    op.create_table('auth_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('client', sa.Text(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('expires_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('revoked_at', app.db.types.UTCDateTime(), nullable=True),
    sa.CheckConstraint("client IN ('web','android')", name='ck_auth_session_client'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    sqlite_strict=True
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_i18n', sa.Text(), nullable=True),
    sa.Column('default_cost_type', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('archived_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.CheckConstraint("default_cost_type IS NULL OR default_cost_type IN ('fixed','variable','one_time')", name='ck_category_cost_type'),
    sa.CheckConstraint("kind IN ('expense','income')", name='ck_category_kind'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'name'),
    sqlite_strict=True
    )
    op.create_table('earmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('target_amount', sa.Integer(), nullable=True),
    sa.Column('archived_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['currency'], ['currency.code'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sqlite_strict=True
    )
    op.create_table('fx_rate',
    sa.Column('date', app.db.types.ISODate(), nullable=False),
    sa.Column('base', sa.Text(), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('rate', app.db.types.DecimalText(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.CheckConstraint("source IN ('ecb','cbr','manual')", name='ck_fx_rate_source'),
    sa.ForeignKeyConstraint(['base'], ['currency.code'], ),
    sa.ForeignKeyConstraint(['quote'], ['currency.code'], ),
    sa.PrimaryKeyConstraint('date', 'base', 'quote'),
    sqlite_strict=True
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('start_date', app.db.types.ISODate(), nullable=True),
    sa.Column('end_date', app.db.types.ISODate(), nullable=True),
    sa.Column('budget_amount', sa.Integer(), nullable=True),
    sa.Column('budget_currency', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('archived_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.CheckConstraint("kind IN ('renovation','trip','event','other')", name='ck_project_kind'),
    sa.ForeignKeyConstraint(['budget_currency'], ['currency.code'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sqlite_strict=True
    )
    op.create_table('security',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('isin', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('price_source', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['currency'], ['currency.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin'),
    sqlite_strict=True
    )
    op.create_table('txn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', app.db.types.ISODate(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('counterparty', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('fx_diff_ref', sa.Integer(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('import_row_id', sa.Integer(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.CheckConstraint("kind IN ('expense','income','transfer','debt_payment','debt_drawdown','investment','asset_purchase','earmark','adjustment','mixed')", name='ck_txn_kind'),
    sa.CheckConstraint("source IN ('manual','import','generated')", name='ck_txn_source'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['import_row_id'], ['import_row.id'], name='fk_txn_import_row', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_strict=True
    )
    with op.batch_alter_table('txn', schema=None) as batch_op:
        batch_op.create_index('ix_txn_date', ['date'], unique=False)

    op.create_table('account_identifier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.CheckConstraint("kind IN ('iban','account_no','card_last4','other')", name='ck_account_identifier_kind'),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'value'),
    sqlite_strict=True
    )
    op.create_table('account_reconciliation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('date', app.db.types.ISODate(), nullable=False),
    sa.Column('stated_balance', sa.Integer(), nullable=False),
    sa.Column('computed_balance', sa.Integer(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('adjustment_txn_id', sa.Integer(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.CheckConstraint("source IN ('manual','statement','anchor')", name='ck_account_reconciliation_source'),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['adjustment_txn_id'], ['txn.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_strict=True
    )
    op.create_table('asset_valuation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('date', app.db.types.ISODate(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.CheckConstraint("source IN ('manual','woz','estimate','import')", name='ck_asset_valuation_source'),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'date'),
    sqlite_strict=True
    )
    op.create_table('budget_template_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('valid_from', sa.Text(), nullable=False),
    sa.Column('valid_to', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['currency'], ['currency.code'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_strict=True
    )
    op.create_table('debt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('lender', sa.Text(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('repayment_type', sa.Text(), nullable=False),
    sa.Column('principal_original', sa.Integer(), nullable=False),
    sa.Column('start_date', app.db.types.ISODate(), nullable=False),
    sa.Column('term_months', sa.Integer(), nullable=True),
    sa.Column('payment_day', sa.Integer(), nullable=True),
    sa.Column('interest_category_id', sa.Integer(), nullable=True),
    sa.Column('linked_asset_id', sa.Integer(), nullable=True),
    sa.Column('parent_debt_id', sa.Integer(), nullable=True),
    sa.Column('lender_identifier', sa.Text(), nullable=True),
    sa.Column('closed_at', app.db.types.ISODate(), nullable=True),
    sa.Column('archived_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.CheckConstraint("repayment_type IN ('annuity','linear','interest_only','free','group')", name='ck_debt_repayment_type'),
    sa.CheckConstraint("type IN ('mortgage','loan','personal','other')", name='ck_debt_type'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['currency'], ['currency.code'], ),
    sa.ForeignKeyConstraint(['interest_category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['linked_asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['parent_debt_id'], ['debt.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sqlite_strict=True
    )
    op.create_table('import_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.Text(), nullable=True),
    sa.Column('file_name', sa.Text(), nullable=True),
    sa.Column('file_sha256', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('stats', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('ai_batch_id', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.CheckConstraint("mode IS NULL OR mode IN ('match','sheet_only')", name='ck_import_batch_mode'),
    sa.CheckConstraint("source IN ('abn_mt940','abn_xls','bunq_csv','bunq_mt940','bunq_api','ics_pdf','gsheet','generic_csv')", name='ck_import_batch_source'),
    sa.CheckConstraint("status IN ('parsing','reviewing','committed','discarded','failed')", name='ck_import_batch_status'),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_strict=True
    )
    op.create_table('investment_trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('txn_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('units', app.db.types.DecimalText(), nullable=False),
    sa.Column('price', app.db.types.DecimalText(), nullable=False),
    sa.Column('fees', sa.Integer(), nullable=False),
    sa.CheckConstraint("action IN ('buy','sell','dividend_reinvest','split','opening')", name='ck_investment_trade_action'),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], ),
    sa.ForeignKeyConstraint(['txn_id'], ['txn.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_strict=True
    )
    op.create_table('security_price',
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('date', app.db.types.ISODate(), nullable=False),
    sa.Column('price', app.db.types.DecimalText(), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], ),
    sa.PrimaryKeyConstraint('security_id', 'date'),
    sqlite_strict=True
    )
    op.create_table('txn_leg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('txn_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('amount_ref', sa.Integer(), nullable=False),
    sa.Column('ref_estimated', sa.Integer(), nullable=False),
    sa.Column('inferred', sa.Integer(), nullable=False),
    sa.CheckConstraint('amount <> 0', name='ck_txn_leg_nonzero'),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['txn_id'], ['txn.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_strict=True
    )
    with op.batch_alter_table('txn_leg', schema=None) as batch_op:
        batch_op.create_index('ix_leg_account', ['account_id'], unique=False)

    op.create_table('ai_call_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_strict=True
    )
    op.create_table('budget_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('template_line_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['currency'], ['currency.code'], ),
    sa.ForeignKeyConstraint(['template_line_id'], ['budget_template_line.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month', 'category_id', 'currency', 'template_line_id'),
    sqlite_strict=True
    )
    op.create_table('debt_balance_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debt_id', sa.Integer(), nullable=False),
    sa.Column('date', app.db.types.ISODate(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['debt_id'], ['debt.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('debt_id', 'date'),
    sqlite_strict=True
    )
    op.create_table('debt_rate_period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debt_id', sa.Integer(), nullable=False),
    sa.Column('from_date', app.db.types.ISODate(), nullable=False),
    sa.Column('annual_rate', app.db.types.DecimalText(), nullable=False),
    sa.ForeignKeyConstraint(['debt_id'], ['debt.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('debt_id', 'from_date'),
    sqlite_strict=True
    )
    op.create_table('import_row',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('raw', sa.Text(), nullable=False),
    sa.Column('date', app.db.types.ISODate(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('counterparty', sa.Text(), nullable=True),
    sa.Column('counterparty_iban', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('dedupe_key', sa.Text(), nullable=False),
    sa.Column('stated_balance', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('proposed', sa.Text(), nullable=True),
    sa.Column('matched_row_id', sa.Integer(), nullable=True),
    sa.Column('matched_txn_id', sa.Integer(), nullable=True),
    sa.Column('match_score', sa.Text(), nullable=True),
    sa.Column('generated', sa.Integer(), nullable=False),
    sa.Column('txn_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('new','duplicate','suggested','accepted','skipped','committed')", name='ck_import_row_status'),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_row_id'], ['import_row.id'], ),
    sa.ForeignKeyConstraint(['matched_txn_id'], ['txn.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['txn_id'], ['txn.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_strict=True
    )
    with op.batch_alter_table('import_row', schema=None) as batch_op:
        batch_op.create_index('ix_import_row_dedupe', ['dedupe_key'], unique=False)
        batch_op.create_index('ux_import_external', ['account_id', 'external_id'], unique=True, sqlite_where=sa.text("external_id IS NOT NULL AND status = 'committed'"))

    op.create_table('txn_split',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('txn_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('amount_ref', sa.Integer(), nullable=False),
    sa.Column('ref_estimated', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('debt_id', sa.Integer(), nullable=True),
    sa.Column('earmark_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('cost_type', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.CheckConstraint("cost_type IS NULL OR cost_type IN ('fixed','variable','one_time')", name='ck_txn_split_cost_type'),
    sa.CheckConstraint('(category_id IS NOT NULL) + (debt_id IS NOT NULL) + (earmark_id IS NOT NULL) + (asset_id IS NOT NULL) = 1', name='ck_txn_split_one_target'),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['currency'], ['currency.code'], ),
    sa.ForeignKeyConstraint(['debt_id'], ['debt.id'], ),
    sa.ForeignKeyConstraint(['earmark_id'], ['earmark.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['txn_id'], ['txn.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_strict=True
    )
    with op.batch_alter_table('txn_split', schema=None) as batch_op:
        batch_op.create_index('ix_split_category', ['category_id'], unique=False)
        batch_op.create_index('ix_split_project', ['project_id'], unique=False)

    op.create_table('ai_suggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_row_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('cost_type', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('transfer_account_id', sa.Integer(), nullable=True),
    sa.Column('confidence', app.db.types.DecimalText(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['import_row_id'], ['import_row.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['transfer_account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_row_id'),
    sqlite_strict=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_suggestion')
    with op.batch_alter_table('txn_split', schema=None) as batch_op:
        batch_op.drop_index('ix_split_project')
        batch_op.drop_index('ix_split_category')

    op.drop_table('txn_split')
    with op.batch_alter_table('import_row', schema=None) as batch_op:
        batch_op.drop_index('ux_import_external', sqlite_where=sa.text("external_id IS NOT NULL AND status = 'committed'"))
        batch_op.drop_index('ix_import_row_dedupe')

    op.drop_table('import_row')
    op.drop_table('debt_rate_period')
    op.drop_table('debt_balance_snapshot')
    op.drop_table('budget_line')
    op.drop_table('ai_call_log')
    with op.batch_alter_table('txn_leg', schema=None) as batch_op:
        batch_op.drop_index('ix_leg_account')

    op.drop_table('txn_leg')
    op.drop_table('security_price')
    op.drop_table('investment_trade')
    op.drop_table('import_batch')
    op.drop_table('debt')
    op.drop_table('budget_template_line')
    op.drop_table('asset_valuation')
    op.drop_table('account_reconciliation')
    op.drop_table('account_identifier')
    with op.batch_alter_table('txn', schema=None) as batch_op:
        batch_op.drop_index('ix_txn_date')

    op.drop_table('txn')
    op.drop_table('security')
    op.drop_table('project')
    op.drop_table('fx_rate')
    op.drop_table('earmark')
    op.drop_table('category')
    op.drop_table('auth_session')
    op.drop_table('audit_log')
    op.drop_table('asset')
    op.drop_table('account')
    op.drop_table('user')
    op.drop_table('setting')
    op.drop_table('import_rule')
    op.drop_table('currency')
    # ### end Alembic commands ###
